[build]
  command = "bundle exec jekyll build"
  publish = "_site"

[build.environment]
  NODE_VERSION = "14"
  NPM_VERSION = "7"
  JEKYLL_ENV = "production"
  NODE_ENV = "production"
  API_URL = "http://sharetechstack.netlify.app"

[dev]
  port = 8888 # Local dev server port when using `netlify dev`